# Generated by Django 3.2.6 on 2021-08-22 21:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=150)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "ordering": ("timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("image", models.ImageField(upload_to="uploads/%Y")),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-approved_date", "-timestamp"),
                "permissions": (("can_approve_photo", "Can approve photo"),),
            },
        ),
    ]
