# Generated by Django 3.2.6 on 2021-08-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="uploads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="photos.photo"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments+", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
